{% set name = "userspacefs" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33ec27c67b0f88791864dfd47b12b8725e2a3927394a872d3842abeba37ec219

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - fusepyng >=1.0.7,<2

test:
  imports:
    - userspacefs

about:
  home: https://github.com/rianhunter/userspacefs
  license: GPL-3.0
  license_family: GPL
  # https://github.com/rianhunter/userspacefs/pull/3
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Cross-platform user-space file systems for Python
  description: |
    userspacefs is a library that allows you to easily write cross-platform
    user-space file systems in Python. macOS and Linux has been tested, but it
    has been designed to run on Windows and other POSIX platforms.

    It is primarily used to power dbxfs.
  dev_url: https://github.com/rianhunter/userspacefs

extra:
  recipe-maintainers:
    - djsutherland
