travis:
  secure:
    BINSTAR_TOKEN: WPsOFw3E4XmNDA6kddVXnT8g+DLmY8zimSvJ3l3NNXpQM8+ZT6+oBSPaoSd/jtw5buRd8+mTm4f+B6fsoQrYk+uezlx6RdladHYEkT8r1a8tgWOC0lgLXxQzph/MBzCmbhmzV4S64FqwW2vabbMdftllVqS5FyopdZ6cmPhPXmLkkJ5ksmnLcGSrN60qhHd7EtfIHxkVE79MvOw3CiyrNkWHgxOvoDiTLDm6+ZAs2Lc692WgTsc53RPvnk/YeJE8G15vYK5k0rZnB+I3hczocngA8WKMCdEbob/bUOPLggRZ0owhHeVS2dxb5vBbOAwIe9iAjM4DYRt5wSnpGNkvrjWuZJ2/FMvscqwCa8cFlh3vEcDVZ7F9xt05+RwC3YE8FEDHS5MPaLXXIdaaRlYg/KCmID3+Y4HYasaOe+8Vqzy2wDhLSeegkeJQ5yTzCmXL/1+sBXVedD/i3ZbjYjHwqGSaoh3Equ5ar7zpUOQxp56+mHd2m+L5h3f6boWgC53C2aKQLFFd6WFydAVDQxrNlDIo3PFLc0NEBSb5f3iYYed0JFkc3H9oFvOivX7j/XjL14VMK5NezgudGCKkuu18LPMbb5/dzoHbgVuFarAmOUogUHaE1aDfVqE4i0SSAsBCdWb2IPfjEsctX154+fU5nLgZ2TESlBX9oFSHl+sEmYs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
